### ISSUE TITLE
Improve batch saving

### ISSUE THREAD

**Issue by aih** [aih/billsim#21]
See https://github.com/aih/billsim/blob/main/src/billsim/utils_db.py#L382

We currently use sqlalchemy for this batch save operation. However, in some cases, it causes errors:
```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.9.1/envs/py391/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/home/ubuntu/.pyenv/versions/3.9.1/envs/py391/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StatementTooComplex: stack depth limit exceeded
HINT:  Increase the configuration parameter "max_stack_depth" (currently 2048kB), after ensuring the platform's stack depth limit is adequate.
```

We may try to increase max_stack_depth, but the statements also appear to be unnecessarily large and recursive.

Can we take advantage of psycopg3 improvements and use it directly for saves?

**Comment by aih** [comment]
On a current server:

```
$ ulimit -s
8192
```
